IF DB_ID('FlashcardApp') IS NULL
    CREATE DATABASE FlashcardApp;
GO

USE FlashcardApp;
GO

IF OBJECT_ID('dbo.Users', 'U') IS NULL
CREATE TABLE Users
(
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
);
GO

IF OBJECT_ID('dbo.Decks', 'U') IS NULL
CREATE TABLE Decks
(
    DeckID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    Title NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT FK_Decks_Users FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);
GO

IF OBJECT_ID('dbo.Cards', 'U') IS NULL
CREATE TABLE Cards
(
    CardID INT IDENTITY(1,1) PRIMARY KEY,
    DeckID INT NOT NULL,
    Front NVARCHAR(MAX) NOT NULL,
    Back NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT FK_Cards_Decks FOREIGN KEY (DeckID) REFERENCES Decks(DeckID) ON DELETE CASCADE
);
GO

IF OBJECT_ID('dbo.DeckDownloads', 'U') IS NULL
CREATE TABLE DeckDownloads
(
    DownloadID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    DeckID INT NOT NULL,
    DownloadedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    CONSTRAINT UQ_DeckDownloads_User_Deck UNIQUE (UserID, DeckID),
    CONSTRAINT FK_DeckDownloads_Users FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE NO ACTION,
    CONSTRAINT FK_DeckDownloads_Decks FOREIGN KEY (DeckID) REFERENCES Decks(DeckID) ON DELETE CASCADE
);
GO

IF OBJECT_ID('dbo.Logs', 'U') IS NULL
CREATE TABLE Logs
(
    LogID BIGINT IDENTITY(1,1) PRIMARY KEY,
    TableName NVARCHAR(128) NOT NULL,
    OperationType NVARCHAR(10) NOT NULL,
    AffectedRows INT NOT NULL,
    ChangedBy NVARCHAR(128) NOT NULL DEFAULT SUSER_SNAME(),
    ChangedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    DetailsJson NVARCHAR(MAX) NULL
);
GO